# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 640006065c511b5e11f103a8ee07bf81d3608c7b6d2e2ae026847a0fae7805a3574ec6b1549cf7cb026736f29f49876c6b6086c4a936890a748de8ca39735c95

test:
  secret_key_base: 20ed4a21a1c4da6a1c535d8d1506612d1111bf3c34434cc54028ede2f9d38f30ade19fb18ec365f5748223917ae5f6c25d027259c30282aa154cf2e52f1d9e17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
